GkAnket/Models/AnketItemModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Web;

namespace GkAnket.Models
{
    public class AnketItemModel
    {
        
        public Guid Id { get; set; }

        [DisplayName("Anket Adı")]
        public string AnketAdi { get; set; }

        [DisplayName("Cevaplayan Sayısı")]
        public int Cevaplayan { get; set; }

        [DisplayName("Cevaplanmamış Sayısı")]
        public int Bekleyen { get; set; }

        [DisplayName("ToplamKisi Sayısı")]
        public int ToplamKisi { get { return (this.Bekleyen + this.Cevaplayan);  } }
    }
}

GkAnket/Models/CevaplanacakAnketlerim.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Web;


namespace GkAnket.Models
{
    public class CevaplanacakAnketlerim
    {
        public Guid Id { get; set; }

        [DisplayName("AnketAdı")]
        public string AnketAdi { get; set; }

        [DisplayName("Oluşturlan Tarih")]
        public string OlusturulanTarih { get; set; }


    }
}

GkAnket/Models/Kisilistesi.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Web;

namespace GkAnket.Models
{
    public class Kisilistesi
    {
        public Guid Id { get; set; }

        [DisplayName("Uye Adı")]
        public string UyeAdi { get; set; }

        [DisplayName("Uye Soyadı")]
        public string UyeSoyadi { get; set; }

        [DisplayName("Bölümü")]
        public string Bolumu { get; set; }

        [DisplayName("Sınıfı")]
        public int Sinifi { get; set; }

    }
}

GkAnket/Models/YeniAnketModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Web;

namespace GkAnket.Models
{
    public class YeniAnketModel
    {

        [DisplayName("Adı")]
        public int Adi { get; set; }


        [DisplayName("Açıklama")]
        public int Aciklama { get; set; }

    }
}

GkAnket/Controllers/AnketlerimController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GkAnket.Controllers
{
    public class AnketlerimController : Controller
    {
        public ActionResult Index()
        {

            var anketler = new List<GkAnket.Models.AnketItemModel>();

            anketler.Add(new Models.AnketItemModel {
                Id = Guid.NewGuid(),
                AnketAdi = "Anket 1",
                Bekleyen = 10,
                Cevaplayan = 120


            });

            anketler.Add(new Models.AnketItemModel
            {
                Id = Guid.NewGuid(),
                AnketAdi = "Anket 2",
                Bekleyen =70,
                Cevaplayan = 40


            });

            return View(anketler);
        }

        

        
    }
}

GkAnket/Controllers/CevaplanacakAnketlerimController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GkAnket.Controllers
{
    public class CevaplanacakAnketlerimController : Controller
    {
        // GET: CevaplanacakAnketlerim
        public ActionResult Index()
        {
            var anketler = new List<GkAnket.Models.CevaplanacakAnketlerim>();

            anketler.Add(new Models.CevaplanacakAnketlerim { 
                Id = Guid.NewGuid(),
                AnketAdi = "Gönüllük Eğitimi",
                OlusturulanTarih = "10.12.1016",

            });

            anketler.Add(new Models.CevaplanacakAnketlerim
            {
                Id = Guid.NewGuid(),
                AnketAdi = "Afad Eğitimi",
                OlusturulanTarih = "10.10.2016",

            });
            return View(anketler);
        }
    }
}

GkAnket/Controllers/GuvenlikController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GkAnket.Controllers
{
    public class GuvenlikController : Controller
    {
        // GET: Guvenlik
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Cikis()
        {
            ViewBag.Message = "Hoşçakalın..:)";
            return View();
        }
    }
}

GkAnket/Controllers/KisiListesiController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GkAnket.Controllers
{
    public class KisiListesiController : Controller
    {
        // GET: KisiListesi
        public ActionResult Index()
        {
            var anketler = new List<GkAnket.Models.Kisilistesi>();

            anketler.Add(new Models.Kisilistesi
            {
                Id = Guid.NewGuid(),
                UyeAdi = "Mehmet Enes",
                UyeSoyadi = "Aktas",
                Bolumu = "Bilişim",
                Sinifi = 3,



            });

            anketler.Add(new Models.Kisilistesi
            {
                Id = Guid.NewGuid(),
                UyeAdi = "Ebru Zeynep",
                UyeSoyadi = "Nair",
                Bolumu = "Bilgisayar",
                Sinifi = 3,

            });
            return View(anketler);
        }
    }
}

GkAnket/Controllers/YeniAnketlerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GkAnket.Controllers
{
    public class YeniAnketlerController : Controller
    {
        // GET: YeniAnketler
        public ActionResult Index()
        {
            return View();
        }
    }
}

GkAnket/Views/Anketlerim/Index.cshtml
@model List<GkAnket.Models.AnketItemModel>
@using GridMvc.Html

@{
    ViewBag.Title = "Anketlerim";
}

@Html.Grid(Model).Columns(columns =>
{
columns.Add(p => p.AnketAdi).Titled("Anket Adı").SetWidth(110);
columns.Add(p => p.Cevaplayan).Titled("Cevaplayan Sayısı").Sortable(true);
columns.Add(p => p.Bekleyen).Titled("Bekleyen Sayısı").Sortable(true);
columns.Add(p => p.ToplamKisi).Titled("Toplam Kisi Sayısı").Sortable(true);
columns.Add(p => p.Id).Titled(" ").Encoded(false)
    .Sanitized(false)
    .SetWidth(150)
    .RenderValueAs(o => @<div><div class="btn btn-info" onclick="alert(' @o.Id.ToString() Id için düzenleme İşlemi ')" >Düzenle</div><div class="btn btn-danger" onclick="alert(' @o.Id.ToString() Id için silme işlemi')">Sil</div></div>);
}).WithPaging(20)

GkAnket/Views/CevaplanacakAnketlerim/Index.cshtml
@model List<GkAnket.Models.CevaplanacakAnketlerim>
@using GridMvc.Html

@{
    ViewBag.Title = "Cevaplanacak Anketler";
}

<h2>Cevaplanacak Anketler</h2>


@Html.Grid(Model).Columns(columns =>
{
columns.Add(p => p.AnketAdi).Titled("Anket Adı");
columns.Add(p => p.OlusturulanTarih).Titled("OlusturulanTarih").Sortable(true);
columns.Add(p => p.Id).Titled(" ").Encoded(false)
    .Sanitized(false)
    .SetWidth(80)
    .RenderValueAs(o => @<div><div class="btn btn-info" onclick="alert(' @o.Id.ToString() Cevap için anket ekranına yönlendiriliyorsunuz ')">Cevapla</div></div>);
}).WithPaging(20)

GkAnket/Views/Guvenlik/Cikis.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Çıkış</title>
</head>
<body>
    <div> <h1>@ViewBag.Message </h1>
    </div>
</body>
</html>

GkAnket/Views/KisiListesi/Index.cshtml
@model List<GkAnket.Models.Kisilistesi>
@using GridMvc.Html
@{
    ViewBag.Title = "KişiListesi";
}

<h2>Kişi Listesi</h2>



@Html.Grid(Model).Columns(columns =>
{
columns.Add(p =>p.UyeAdi).Titled("Üye Adı").SetWidth(110);
columns.Add(p => p.UyeSoyadi).Titled("Üye Soyadı").Sortable(true);
columns.Add(p => p.Bolumu).Titled("Bölümü").Sortable(true);
columns.Add(p => p.Sinifi).Titled("Sinifi").Sortable(true);
}).WithPaging(20)

GkAnket/Views/Shared/_Grid.cshtml
@using GridMvc.Columns
@model GridMvc.IGrid
@if (Model == null) { return; }
@if (Model.RenderOptions.RenderRowsOnly)
{
    @RenderGridBody();
}
else
{
    <div class="grid-mvc" data-lang="@Model.Language" data-gridname="@Model.RenderOptions.GridName" data-selectable="@Model.RenderOptions.Selectable.ToString().ToLower()" data-multiplefilters ="@Model.RenderOptions.AllowMultipleFilters.ToString().ToLower()">
        <div class="grid-wrap">
            <table class="table table-striped grid-table">
                @* Draw grid header *@
                <thead>
                    @RenderGridHeader()
                </thead>
                <tbody>
                    @RenderGridBody()
                </tbody>
            </table>
            @RenderGridPager()
        </div>
    </div>
}
@helper RenderGridBody()
{
    if (!Model.ItemsToDisplay.Any())
    {
    <tr class="grid-empty-text">
        <td colspan="@Model.Columns.Count()">
            @Model.EmptyGridText
        </td>
    </tr>
    }
    else
    {
        foreach (object item in Model.ItemsToDisplay)
        {
    <tr class="grid-row @Model.GetRowCssClasses(item)">
        @foreach (IGridColumn column in Model.Columns)
        {
            @column.CellRenderer.Render(column, column.GetCell(item))
        }
    </tr>
        }
    }
}
@helper RenderGridHeader()
{
    <tr>
        @foreach (IGridColumn column in Model.Columns)
        {
            @column.HeaderRenderer.Render(column)
        }
    </tr>
}
@helper RenderGridPager()
{
    if (Model.EnablePaging && Model.Pager != null)
    {
    <div class="grid-footer">
        @Html.Partial(Model.Pager.TemplateName, Model.Pager)
    </div>
    }
}

GkAnket/Views/Shared/_GridPager.cshtml
@model GridMvc.Pagination.GridPager
@if (Model == null || Model.PageCount <= 1)
{
    return;
}
<div class="grid-pager">
    <ul class="pagination">
        @if (Model.CurrentPage > 1)
        {
            <li>
                <a href="@Model.GetLinkForPage(Model.CurrentPage - 1)">«</a>
            </li>
        }

        @if (Model.StartDisplayedPage > 1)
        {
            <li>
                <a href="@Model.GetLinkForPage(1)">1</a>
            </li>
            if (Model.StartDisplayedPage > 2)
            {
            <li><a href="@Model.GetLinkForPage(Model.StartDisplayedPage - 1)">...</a></li>
            }
        }
        @for (int i = Model.StartDisplayedPage; i <= Model.EndDisplayedPage; i++)
        {
            if (i == Model.CurrentPage)
            {
            <li class="active"><span>@i</span></li>
            }
            else
            {
            <li><a href="@Model.GetLinkForPage(i)">@i</a></li>
            }
        }
        @if (Model.EndDisplayedPage < Model.PageCount)
        {
            if (Model.EndDisplayedPage < Model.PageCount - 1)
            {
            <li><a href="@Model.GetLinkForPage(Model.EndDisplayedPage + 1)">...</a></li>
            }
            <li><a href="@Model.GetLinkForPage(Model.PageCount)">@Model.PageCount</a></li>
        }
        @if (Model.CurrentPage < Model.PageCount)
        {
            <li><a href="@Model.GetLinkForPage(Model.CurrentPage + 1)">»</a></li>
        }
    </ul>
</div>

GkAnket/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title </title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <link href="~/Content/Gridmvc.css" rel="stylesheet" />
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("GençKal Sakarya Anket Portalı", "Index", "Anketlerim", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav pull-right">
                    <li>@Html.ActionLink("Çıkış", "Cikis", "Guvenlik")</li>                    
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content " style="padding:5px">
      
        <div class="col-xs-3">
            <!-- required for floating -->
            <!-- Nav tabs -->
          <ul class="nav nav-pills nav-stacked">
              @{ string controller = ViewContext.RouteData.Values["Controller"].ToString();
                  string action = ViewContext.RouteData.Values["Action"].ToString();}

                <li class="@((controller == "Anketlerim" && action == "Index") ? "active" : "")">@Html.ActionLink("Anketlerim", "Index", "Anketlerim")</li>
              <li class="@((controller == "YeniAnketler" && action == "Index") ? "active" : "")">@Html.ActionLink("Yeni Anket Kaydı", "Index", "YeniAnketler")</li>
              <li class="@((controller == "KişiListesi" && action == "Index") ? "active" : "")">@Html.ActionLink("Kişi Listesi", "Index", "KisiListesi")</li>
              <li class="@((controller == "CevaplanacakAnketlerim" && action == "Index") ? "active" : "")">@Html.ActionLink("Cevaplanacak Anketlerim", "Index", "CevaplanacakAnketlerim")</li>
            </ul>
        </div>

        <div class="col-xs-9 table-bordered">
       
          @RenderBody()
        </div>  
        <footer>
            <p>&copy; @DateTime.Now.Year </p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        <script src="~/Scripts/gridmvc.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>

GkAnket/Views/YeniAnketler/Index.cshtml
@model GkAnket.Models.YeniAnketModel
@{
    ViewBag.Title = "Yeni Anketler";
}

<h2>Yeni Anket Kaydı</h2>
@using (Html.BeginForm())
{
     
<div class="row"  style="padding:5px">
    <div class="col-xs-4">@Html.LabelFor(p => p.Adi, new { style = "width:100%" })</div>
    <div class="col-xs-8">@Html.TextBoxFor(p => p.Adi, new { style = "width:100%" })</div>
</div>

<div class="row" style="padding:5px">
    <div class="col-xs-4">@Html.LabelFor(p => p.Aciklama, new { style ="width:100%" })</div>
    <div class="col-xs-8">@Html.TextAreaFor(p => p.Aciklama, new { style = "width:100%" })</div>
</div>
<div class="row text-center">
    <div class="col-xs-12 text-center"><button class="btn btn-success" type="submit"> Kayıt </button></div>
    
</div>
<div style="margin-top:70px"></div>
}